/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_OCP_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[4] = {-1.2999999999999999e-02, 1.2999999999999999e-02, -1.2999999999999999e-02, 1.2999999999999999e-02};
static const casadi_real casadi_c1[4] = {2.3499999999999999e-01, 0., -2.3499999999999999e-01, 0.};
static const casadi_real casadi_c2[4] = {0., 2.3499999999999999e-01, 0., -2.3499999999999999e-01};

/* quad_OCP_expl_vde_adj:(i0[13],i1[13],i2[4],i3[])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, w2, *w3=w+13, *w4=w+22, *w5=w+35, *w6=w+38, *w7=w+42, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+55, *w19=w+59, *w20=w+62, *w21=w+71, *w22=w+74, w23, w24, w25, w26, w27, w28, w29, w30, *w31=w+85, *w32=w+89, *w33=w+93, *w34=w+97, *w35=w+101, *w36=w+117;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 13, w4);
  /* #5: {@5, @6, @7, @8, @9, @10} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  casadi_copy(w4+7, 3, w7);
  w8 = w4[10];
  w9 = w4[11];
  w10 = w4[12];
  /* #6: @11 = 0 */
  w11 = 0.;
  /* #7: @12 = 0 */
  w12 = 0.;
  /* #8: @13 = 20 */
  w13 = 20.;
  /* #9: @14 = input[2][0] */
  w14 = arg[2] ? arg[2][0] : 0;
  /* #10: @15 = input[2][1] */
  w15 = arg[2] ? arg[2][1] : 0;
  /* #11: @16 = input[2][2] */
  w16 = arg[2] ? arg[2][2] : 0;
  /* #12: @17 = input[2][3] */
  w17 = arg[2] ? arg[2][3] : 0;
  /* #13: @18 = vertcat(@14, @15, @16, @17) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #14: @18 = (@13*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #15: @14 = @18[0] */
  for (rr=(&w14), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #16: @15 = @18[1] */
  for (rr=(&w15), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #17: @14 = (@14+@15) */
  w14 += w15;
  /* #18: @15 = @18[2] */
  for (rr=(&w15), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #19: @14 = (@14+@15) */
  w14 += w15;
  /* #20: @15 = @18[3] */
  for (rr=(&w15), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #21: @14 = (@14+@15) */
  w14 += w15;
  /* #22: @19 = vertcat(@11, @12, @14) */
  rr=w19;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w14;
  /* #23: @19 = @19' */
  /* #24: @3 = mac(@7,@19,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w19+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #25: @20 = @3' */
  for (i=0, rr=w20, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #26: {@19, @21, @22} = horzsplit(@20) */
  casadi_copy(w20, 3, w19);
  casadi_copy(w20+3, 3, w21);
  casadi_copy(w20+6, 3, w22);
  /* #27: @22 = @22' */
  /* #28: {@11, @12, @14} = horzsplit(@22) */
  w11 = w22[0];
  w12 = w22[1];
  w14 = w22[2];
  /* #29: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #30: @15 = (@2*@12) */
  w15  = (w2*w12);
  /* #31: @16 = @1[2] */
  for (rr=(&w16), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #32: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #33: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #34: @15 = (@15-@17) */
  w15 -= w17;
  /* #35: @21 = @21' */
  /* #36: {@17, @23, @24} = horzsplit(@21) */
  w17 = w21[0];
  w23 = w21[1];
  w24 = w21[2];
  /* #37: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #38: @25 = (@2*@24) */
  w25  = (w2*w24);
  /* #39: @15 = (@15-@25) */
  w15 -= w25;
  /* #40: @25 = @1[3] */
  for (rr=(&w25), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #41: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #42: @26 = (@25*@17) */
  w26  = (w25*w17);
  /* #43: @15 = (@15+@26) */
  w15 += w26;
  /* #44: @19 = @19' */
  /* #45: {@26, @27, @28} = horzsplit(@19) */
  w26 = w19[0];
  w27 = w19[1];
  w28 = w19[2];
  /* #46: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #47: @29 = (@16*@28) */
  w29  = (w16*w28);
  /* #48: @15 = (@15+@29) */
  w15 += w29;
  /* #49: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #50: @29 = (@25*@27) */
  w29  = (w25*w27);
  /* #51: @15 = (@15-@29) */
  w15 -= w29;
  /* #52: (@0[0] += @15) */
  for (rr=w0+0, ss=(&w15); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #53: @15 = (2.*@2) */
  w15 = (2.* w2 );
  /* #54: @14 = (-@14) */
  w14 = (- w14 );
  /* #55: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #56: @15 = (@15*@14) */
  w15 *= w14;
  /* #57: @29 = @1[0] */
  for (rr=(&w29), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #58: @30 = (@29*@12) */
  w30  = (w29*w12);
  /* #59: @15 = (@15+@30) */
  w15 += w30;
  /* #60: @30 = (@25*@11) */
  w30  = (w25*w11);
  /* #61: @15 = (@15+@30) */
  w15 += w30;
  /* #62: @30 = (@29*@24) */
  w30  = (w29*w24);
  /* #63: @15 = (@15-@30) */
  w15 -= w30;
  /* #64: @30 = (2.*@2) */
  w30 = (2.* w2 );
  /* #65: @23 = (-@23) */
  w23 = (- w23 );
  /* #66: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #67: @30 = (@30*@23) */
  w30 *= w23;
  /* #68: @15 = (@15+@30) */
  w15 += w30;
  /* #69: @30 = (@16*@17) */
  w30  = (w16*w17);
  /* #70: @15 = (@15+@30) */
  w15 += w30;
  /* #71: @30 = (@25*@28) */
  w30  = (w25*w28);
  /* #72: @15 = (@15+@30) */
  w15 += w30;
  /* #73: @30 = (@16*@27) */
  w30  = (w16*w27);
  /* #74: @15 = (@15+@30) */
  w15 += w30;
  /* #75: (@0[1] += @15) */
  for (rr=w0+1, ss=(&w15); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #76: @15 = (@16*@12) */
  w15  = (w16*w12);
  /* #77: @30 = (@2*@11) */
  w30  = (w2*w11);
  /* #78: @15 = (@15+@30) */
  w15 += w30;
  /* #79: @30 = (@16*@24) */
  w30  = (w16*w24);
  /* #80: @15 = (@15+@30) */
  w15 += w30;
  /* #81: @30 = (2.*@25) */
  w30 = (2.* w25 );
  /* #82: @30 = (@30*@23) */
  w30 *= w23;
  /* #83: @15 = (@15+@30) */
  w15 += w30;
  /* #84: @30 = (@29*@17) */
  w30  = (w29*w17);
  /* #85: @15 = (@15+@30) */
  w15 += w30;
  /* #86: @30 = (@2*@28) */
  w30  = (w2*w28);
  /* #87: @15 = (@15+@30) */
  w15 += w30;
  /* #88: @30 = (@29*@27) */
  w30  = (w29*w27);
  /* #89: @15 = (@15-@30) */
  w15 -= w30;
  /* #90: @30 = (2.*@25) */
  w30 = (2.* w25 );
  /* #91: @26 = (-@26) */
  w26 = (- w26 );
  /* #92: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #93: @30 = (@30*@26) */
  w30 *= w26;
  /* #94: @15 = (@15+@30) */
  w15 += w30;
  /* #95: (@0[3] += @15) */
  for (rr=w0+3, ss=(&w15); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #96: @15 = (2.*@16) */
  w15 = (2.* w16 );
  /* #97: @15 = (@15*@14) */
  w15 *= w14;
  /* #98: @12 = (@25*@12) */
  w12  = (w25*w12);
  /* #99: @15 = (@15+@12) */
  w15 += w12;
  /* #100: @11 = (@29*@11) */
  w11  = (w29*w11);
  /* #101: @15 = (@15-@11) */
  w15 -= w11;
  /* #102: @24 = (@25*@24) */
  w24  = (w25*w24);
  /* #103: @15 = (@15+@24) */
  w15 += w24;
  /* #104: @17 = (@2*@17) */
  w17  = (w2*w17);
  /* #105: @15 = (@15+@17) */
  w15 += w17;
  /* #106: @28 = (@29*@28) */
  w28  = (w29*w28);
  /* #107: @15 = (@15+@28) */
  w15 += w28;
  /* #108: @27 = (@2*@27) */
  w27  = (w2*w27);
  /* #109: @15 = (@15+@27) */
  w15 += w27;
  /* #110: @27 = (2.*@16) */
  w27 = (2.* w16 );
  /* #111: @27 = (@27*@26) */
  w27 *= w26;
  /* #112: @15 = (@15+@27) */
  w15 += w27;
  /* #113: (@0[2] += @15) */
  for (rr=w0+2, ss=(&w15); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #114: @18 = zeros(4x1) */
  casadi_clear(w18, 4);
  /* #115: @15 = 0 */
  w15 = 0.;
  /* #116: @19 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w19);
  /* #117: @27 = @19[0] */
  for (rr=(&w27), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #118: @27 = (-@27) */
  w27 = (- w27 );
  /* #119: @26 = @19[1] */
  for (rr=(&w26), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #120: @26 = (-@26) */
  w26 = (- w26 );
  /* #121: @28 = @19[2] */
  for (rr=(&w28), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #122: @28 = (-@28) */
  w28 = (- w28 );
  /* #123: @31 = horzcat(@15, @27, @26, @28) */
  rr=w31;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #124: @31 = @31' */
  /* #125: @15 = @19[0] */
  for (rr=(&w15), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #126: @27 = 0 */
  w27 = 0.;
  /* #127: @26 = @19[2] */
  for (rr=(&w26), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #128: @28 = @19[1] */
  for (rr=(&w28), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #129: @28 = (-@28) */
  w28 = (- w28 );
  /* #130: @32 = horzcat(@15, @27, @26, @28) */
  rr=w32;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #131: @32 = @32' */
  /* #132: @15 = @19[1] */
  for (rr=(&w15), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #133: @27 = @19[2] */
  for (rr=(&w27), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #134: @27 = (-@27) */
  w27 = (- w27 );
  /* #135: @26 = 0 */
  w26 = 0.;
  /* #136: @28 = @19[0] */
  for (rr=(&w28), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #137: @33 = horzcat(@15, @27, @26, @28) */
  rr=w33;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #138: @33 = @33' */
  /* #139: @15 = @19[2] */
  for (rr=(&w15), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #140: @27 = @19[1] */
  for (rr=(&w27), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #141: @26 = @19[0] */
  for (rr=(&w26), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #142: @26 = (-@26) */
  w26 = (- w26 );
  /* #143: @28 = 0 */
  w28 = 0.;
  /* #144: @34 = horzcat(@15, @27, @26, @28) */
  rr=w34;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #145: @34 = @34' */
  /* #146: @35 = horzcat(@31, @32, @33, @34) */
  rr=w35;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<4; ++i) *rr++ = *cs++;
  /* #147: @15 = 0.5 */
  w15 = 5.0000000000000000e-01;
  /* #148: @6 = (@15*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #149: @18 = mac(@35,@6,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #150: @0 = (@0+@18) */
  for (i=0, rr=w0, cs=w18; i<4; ++i) (*rr++) += (*cs++);
  /* #151: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #152: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+4);
  /* #153: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #154: @15 = 0.03 */
  w15 = 2.9999999999999999e-02;
  /* #155: @27 = @19[2] */
  for (rr=(&w27), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #156: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #157: @26 = 33.3333 */
  w26 = 3.3333333333333336e+01;
  /* #158: @26 = (@26*@9) */
  w26 *= w9;
  /* #159: @27 = (@27*@26) */
  w27 *= w26;
  /* #160: (@5[0] += @27) */
  for (rr=w5+0, ss=(&w27); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #161: @27 = @19[0] */
  for (rr=(&w27), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #162: @27 = (@27*@26) */
  w27 *= w26;
  /* #163: @15 = (@15*@27) */
  w15 *= w27;
  /* #164: (@5[2] += @15) */
  for (rr=w5+2, ss=(&w15); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #165: @15 = -0.03 */
  w15 = -2.9999999999999999e-02;
  /* #166: @27 = @19[1] */
  for (rr=(&w27), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #167: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #168: @9 = 33.3333 */
  w9 = 3.3333333333333336e+01;
  /* #169: @9 = (@9*@8) */
  w9 *= w8;
  /* #170: @27 = (@27*@9) */
  w27 *= w9;
  /* #171: (@5[2] += @27) */
  for (rr=w5+2, ss=(&w27); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #172: @27 = @19[2] */
  for (rr=(&w27), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #173: @27 = (@27*@9) */
  w27 *= w9;
  /* #174: @15 = (@15*@27) */
  w15 *= w27;
  /* #175: (@5[1] += @15) */
  for (rr=w5+1, ss=(&w15); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #176: @35 = zeros(4x4) */
  casadi_clear(w35, 16);
  /* #177: @1 = @1' */
  /* #178: @35 = mac(@6,@1,@35) */
  for (i=0, rr=w35; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w6+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #179: @36 = @35' */
  for (i=0, rr=w36, cs=w35; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #180: {@6, @1, @0, @18} = horzsplit(@36) */
  casadi_copy(w36, 4, w6);
  casadi_copy(w36+4, 4, w1);
  casadi_copy(w36+8, 4, w0);
  casadi_copy(w36+12, 4, w18);
  /* #181: @18 = @18' */
  /* #182: {@15, @27, @8, NULL} = horzsplit(@18) */
  w15 = w18[0];
  w27 = w18[1];
  w8 = w18[2];
  /* #183: @8 = (-@8) */
  w8 = (- w8 );
  /* #184: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #185: (@5[1] += @27) */
  for (rr=w5+1, ss=(&w27); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #186: (@5[2] += @15) */
  for (rr=w5+2, ss=(&w15); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #187: @0 = @0' */
  /* #188: {@15, @27, NULL, @8} = horzsplit(@0) */
  w15 = w0[0];
  w27 = w0[1];
  w8 = w0[3];
  /* #189: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #190: @27 = (-@27) */
  w27 = (- w27 );
  /* #191: (@5[2] += @27) */
  for (rr=w5+2, ss=(&w27); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #192: (@5[1] += @15) */
  for (rr=w5+1, ss=(&w15); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #193: @1 = @1' */
  /* #194: {@15, NULL, @27, @8} = horzsplit(@1) */
  w15 = w1[0];
  w27 = w1[2];
  w8 = w1[3];
  /* #195: @8 = (-@8) */
  w8 = (- w8 );
  /* #196: (@5[1] += @8) */
  for (rr=w5+1, ss=(&w8); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #197: (@5[2] += @27) */
  for (rr=w5+2, ss=(&w27); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #198: (@5[0] += @15) */
  for (rr=w5+0, ss=(&w15); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #199: @6 = @6' */
  /* #200: {NULL, @15, @27, @8} = horzsplit(@6) */
  w15 = w6[1];
  w27 = w6[2];
  w8 = w6[3];
  /* #201: @8 = (-@8) */
  w8 = (- w8 );
  /* #202: (@5[2] += @8) */
  for (rr=w5+2, ss=(&w8); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #203: @27 = (-@27) */
  w27 = (- w27 );
  /* #204: (@5[1] += @27) */
  for (rr=w5+1, ss=(&w27); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #205: @15 = (-@15) */
  w15 = (- w15 );
  /* #206: (@5[0] += @15) */
  for (rr=w5+0, ss=(&w15); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #207: output[0][2] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+7);
  /* #208: @15 = 16.6667 */
  w15 = 1.6666666666666668e+01;
  /* #209: @15 = (@15*@10) */
  w15 *= w10;
  /* #210: @6 = [-0.013, 0.013, -0.013, 0.013] */
  casadi_copy(casadi_c0, 4, w6);
  /* #211: @6 = @6' */
  /* #212: @6 = (@15*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #213: @6 = @6' */
  /* #214: @1 = [0.235, 0, -0.235, 0] */
  casadi_copy(casadi_c1, 4, w1);
  /* #215: @1 = @1' */
  /* #216: @1 = (@26*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w26*(*cs++));
  /* #217: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #218: @1 = @1' */
  /* #219: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #220: @1 = [0, 0.235, 0, -0.235] */
  casadi_copy(casadi_c2, 4, w1);
  /* #221: @1 = @1' */
  /* #222: @1 = (@9*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #223: @1 = @1' */
  /* #224: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #225: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #226: @9 = 1 */
  w9 = 1.;
  /* #227: @26 = sq(@16) */
  w26 = casadi_sq( w16 );
  /* #228: @15 = sq(@25) */
  w15 = casadi_sq( w25 );
  /* #229: @26 = (@26+@15) */
  w26 += w15;
  /* #230: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #231: @9 = (@9-@26) */
  w9 -= w26;
  /* #232: @26 = (@2*@16) */
  w26  = (w2*w16);
  /* #233: @15 = (@29*@25) */
  w15  = (w29*w25);
  /* #234: @26 = (@26-@15) */
  w26 -= w15;
  /* #235: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #236: @15 = (@2*@25) */
  w15  = (w2*w25);
  /* #237: @10 = (@29*@16) */
  w10  = (w29*w16);
  /* #238: @15 = (@15+@10) */
  w15 += w10;
  /* #239: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #240: @19 = horzcat(@9, @26, @15) */
  rr=w19;
  *rr++ = w9;
  *rr++ = w26;
  *rr++ = w15;
  /* #241: @19 = @19' */
  /* #242: @9 = (@2*@16) */
  w9  = (w2*w16);
  /* #243: @26 = (@29*@25) */
  w26  = (w29*w25);
  /* #244: @9 = (@9+@26) */
  w9 += w26;
  /* #245: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #246: @26 = 1 */
  w26 = 1.;
  /* #247: @15 = sq(@2) */
  w15 = casadi_sq( w2 );
  /* #248: @10 = sq(@25) */
  w10 = casadi_sq( w25 );
  /* #249: @15 = (@15+@10) */
  w15 += w10;
  /* #250: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #251: @26 = (@26-@15) */
  w26 -= w15;
  /* #252: @15 = (@16*@25) */
  w15  = (w16*w25);
  /* #253: @10 = (@29*@2) */
  w10  = (w29*w2);
  /* #254: @15 = (@15-@10) */
  w15 -= w10;
  /* #255: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #256: @21 = horzcat(@9, @26, @15) */
  rr=w21;
  *rr++ = w9;
  *rr++ = w26;
  *rr++ = w15;
  /* #257: @21 = @21' */
  /* #258: @9 = (@2*@25) */
  w9  = (w2*w25);
  /* #259: @26 = (@29*@16) */
  w26  = (w29*w16);
  /* #260: @9 = (@9-@26) */
  w9 -= w26;
  /* #261: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #262: @25 = (@16*@25) */
  w25  = (w16*w25);
  /* #263: @29 = (@29*@2) */
  w29 *= w2;
  /* #264: @25 = (@25+@29) */
  w25 += w29;
  /* #265: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #266: @29 = 1 */
  w29 = 1.;
  /* #267: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #268: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #269: @2 = (@2+@16) */
  w2 += w16;
  /* #270: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #271: @29 = (@29-@2) */
  w29 -= w2;
  /* #272: @22 = horzcat(@9, @25, @29) */
  rr=w22;
  *rr++ = w9;
  *rr++ = w25;
  *rr++ = w29;
  /* #273: @22 = @22' */
  /* #274: @20 = horzcat(@19, @21, @22) */
  rr=w20;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #275: @5 = mac(@20,@7,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #276: {NULL, NULL, @9} = vertsplit(@5) */
  w9 = w5[2];
  /* #277: (@6[3] += @9) */
  for (rr=w6+3, ss=(&w9); rr!=w6+4; rr+=1) *rr += *ss++;
  /* #278: (@6[2] += @9) */
  for (rr=w6+2, ss=(&w9); rr!=w6+3; rr+=1) *rr += *ss++;
  /* #279: (@6[1] += @9) */
  for (rr=w6+1, ss=(&w9); rr!=w6+2; rr+=1) *rr += *ss++;
  /* #280: (@6[0] += @9) */
  for (rr=w6+0, ss=(&w9); rr!=w6+1; rr+=1) *rr += *ss++;
  /* #281: @6 = (@13*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #282: {@13, @9, @25, @29} = vertsplit(@6) */
  w13 = w6[0];
  w9 = w6[1];
  w25 = w6[2];
  w29 = w6[3];
  /* #283: output[0][3] = @13 */
  if (res[0]) res[0][10] = w13;
  /* #284: output[0][4] = @9 */
  if (res[0]) res[0][11] = w9;
  /* #285: output[0][5] = @25 */
  if (res[0]) res[0][12] = w25;
  /* #286: output[0][6] = @29 */
  if (res[0]) res[0][13] = w29;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_OCP_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_OCP_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_OCP_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_OCP_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_OCP_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_OCP_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_OCP_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_OCP_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_OCP_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quad_OCP_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_OCP_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_OCP_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_OCP_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_OCP_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_OCP_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_OCP_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 133;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
